// Publications data, extracted from CV
window.PUBLICATIONS = [
  { y: 2024, type: "preprint", venue: "bioRxiv",
    title: "Genes required for the formation of virulence-provoking bacterial sphingolipids",
    authors: "Olea-Ozuna RJ, Poggio S, Bergström E, Osorio A, <b>Elufisan TO</b>, Padilla-Gómez J, ... Geiger O." },
  { y: 2023, type: "chapter", venue: "Phyto-Oxylipins (book chapter)",
    title: "Transcriptional Regulation of Phyto-Oxylipins Signaling Pathway",
    authors: "<b>Elufisan TO</b>, Oyedara OO, Oluyide OO." },
  { y: 2023, type: "review", venue: "Process Biochemistry",
    title: "A comprehensive view of Bacillus cereus as a polyhydroxyalkanoate (PHA) producer: a promising alternative to petroplastics",
    authors: "Martínez-Herrera RE, Aemán-Huerta ME, Rutiaga-Quiñones OM, de Luna-Santillana EJ, <b>Elufisan TO</b>." },
  { y: 2023, type: "paper", venue: "Proc. Natl. Acad. Sci. India B: Biol. Sci.",
    title: "Antibacterial and In Silico Evaluation of β-lactamase Inhibitory Potential of Pinus sylvestris L. (Scots Pine) Essential Oil",
    authors: "Oyewole KA, Oyedara OO, Awojide SH, ... <b>Elufisan TO</b>." },
  { y: 2022, type: "paper", venue: "Applied Sciences 12(12):6201",
    title: "Complete Genome Report of a Hydrocarbon-Degrading Sphingobium yanoikuyae S72",
    authors: "Lopez ES, <b>Elufisan TO</b>, Bustos P, Charles CPM, Mendoza-Herrera A, Guo X." },
  { y: 2022, type: "paper", venue: "Int. J. Syst. Evol. Microbiol. 72(12):005608",
    title: "Bdellovibrio reynosensis sp. nov., from a Mexico soil sample",
    authors: "Ajao YO, Rodríguez-Luna IC, <b>Elufisan TO</b>, Sánchez-Varela A, Cortés-Espinosa DV, Camilli A, Guo X." },
  { y: 2022, type: "paper", venue: "Microbiol. Resour. Announc.",
    title: "Draft Genome Sequence of a Polyhydroxyalkanoate-Producing Bacillus cereus Strain Isolated from Nuevo Leon, Mexico",
    authors: "Huerta-alemán ME, Martínez-Herrera RE, <b>Elufisan TO</b>, Gandarilla-Pacheco FL, Quintero-Zapata I, Reyez-López MÁ, de Luna-Santillana EDJ." },
  { y: 2022, type: "chapter", venue: "Medical Biotechnology, Biopharmaceutics, Forensic Science & Bioinformatics (CRC Press)",
    title: "Repositioning antiviral drugs as a rapid and cost-effective approach to discover treatment against SARS-CoV-2 infection",
    authors: "Oyedara OO, Adeyemi FM, Adetunji CO, <b>Elufisan TO</b>." },
  { y: 2021, type: "paper", venue: "Brazilian Journal of Microbiology",
    title: "The decolorization and degradation of azo dyes by two Stenotrophomonas strains isolated from textile effluent (Tepetitla, Mexico)",
    authors: "Vilchis-Carmona JA, Rodríguez-Luna IC, <b>Elufisan TO</b>, Sánchez-Varela A, Bibbins-Martínez M, Rivera G, ... Guo X." },
  { y: 2020, type: "paper", venue: "PeerJ 8:e8102",
    title: "The Polycyclic Aromatic Hydrocarbon (PAH) degradation activities and genome analysis of a novel Stenotrophomonas sp. Pemsol isolated from Mexico",
    authors: "<b>Elufisan TO</b>, Rodríguez-Luna IC, Oyedara OO, Sánchez-Varela A, Hernández-Mendoza A, Dantán-González E, Paz-González AD, Muhammad K, Rivera G, Villalobos-Lopez MA, Guo X." },
  { y: 2019, type: "paper", venue: "Microbiol. Resour. Announc. 8(30):e00529-19",
    title: "Complete Genome Sequence of S. maltophilia Strain SVIA2, Isolated from Crude Oil-Contaminated Soil in Tabasco, Mexico",
    authors: "<b>Elufisan TO</b>, Lozano L, Bustos P, Rodríguez-Luna IC, Sánchez-Varela A, Oyedara OO, Villalobos-López MÁ, Guo X." },
  { y: 2018, type: "paper", venue: "International Journal of Genomics, Article 9402073",
    title: "Whole-Genome Sequencing and Comparative Genome Analysis Provided Insight into the Predatory Features and Genetic Diversity of Two Bdellovibrio Species Isolated from Soil",
    authors: "Oyedara OO, Segura-Cabrera A, Guo X, <b>Elufisan TO</b>, Cantú-González RA, Rodríguez Pérez MA." },
  { y: 2017, type: "paper", venue: "Revista de Aplicación Científica y Técnica 3(8):35-39",
    title: "Identificación de Aeromonas spp. a partir de aislados clínicos y ambientales, en Reynosa, Tamaulipas, México",
    authors: "Sanchez-Varela A, Rodriguez-Luna IC, Ortega-Balleza JL, <b>Elufisan TO</b>, Guo X, Castro-Escarpulli G." },
  { y: 2016, type: "paper", venue: "MicrobiologyOpen 5(6):992-1002",
    title: "Isolation of Bdellovibrio sp. from soil samples in Mexico and their potential applications in control of pathogens",
    authors: "Oyedara OO, Luna-Santillana D, Olguin-Rodriguez O, Guo X, ... <b>Elufisan TO</b>, ... Rodriguez-Perez MA." },
  { y: 2013, type: "paper", venue: "Nigeria Solar Energy Journal 23:6-16",
    title: "Biotechnology: a tool for sustainable algae-based biodiesel production in Nigeria",
    authors: "Ayo-Lawal RA, <b>Elufisan TO</b>, Ogundari I, Adesiyan IM, Famurewa AJ." },
  { y: 2013, type: "paper", venue: "Annual Review & Research in Biology 3(4):860-872",
    title: "Investigation on the ability of Sulfonolipid from Salinibacter ruber to ameliorate the toxic effect of sodium arsenite on sperm count and testosterone level in rat",
    authors: "Oluyide BO, Oloke JK, <b>Elufisan TO</b>, Ogunyemi TF." },
  { y: 2012, type: "review", venue: "African Journal of Microbiology Research 6(23):4833-4844",
    title: "Updates on microbial resistance to drugs",
    authors: "<b>Elufisan TO</b>, Oyelade B, Oyedara OO." },
  { y: 2012, type: "paper", venue: "African Journal of Medical Science 4(2):101-115",
    title: "Susceptibility pattern of Staphylococcus aureus isolated from wound of patient attending treatment at the University College Hospital, Ibadan",
    authors: "<b>Elufisan TO</b>, Adeleke EO." },
  { y: 2012, type: "paper", venue: "INTASCI Journal of Microbiology and Biotechnology 2(5):1-11",
    title: "Phytochemical and antibacterial activities of methanolic leaf extract of Lantana camara Linn",
    authors: "Oyedara OO, <b>Elufisan TO</b>, Abioye OE, Fadare TO, Adeyemi FM." },
  { y: 2012, type: "paper", venue: "JMEAST 1:27-44",
    title: "The epidemiological role of plasmid curing in the identification of Staphylococcus aureus route of infection",
    authors: "<b>Elufisan TO</b>, Adeleke EA." },
  { y: 2012, type: "paper", venue: "American Journal of Information Science 2(4)",
    title: "Techno-microbial hazard of computer keyboard: health risk and policy implication",
    authors: "Awoleye MO, Ogunkambi DA, Ayo-lawal RO, Ololade GO, <b>Elufisan TO</b>." },
  { y: 2012, type: "paper", venue: "Accounting Technology & Information Systems eJournal 4(8)",
    title: "Combating cybercrime in a cashless economy — the role of biometrics",
    authors: "<b>Elufisan TO</b>, Awoleye OM." },
  { y: 2011, type: "paper", venue: "Journal of Bacteriology Research 3(2):28-31",
    title: "The protective effect of beta-glucan on Escherichia coli induced infection",
    authors: "<b>Elufisan TO</b>, Oyelade B, Oloke JK." }
];
